language: go
go:
- 1.x
- tip
os:
- linux
install:
- go get github.com/rakyll/statik
- go get -v ./...
script:
- make test
- make build-all

deploy:
  provider: releases
  api_key:
    secure: cmeM5o1TsJhkW4ys9uNsiaPf144pCEcy4Opt1neMZPL1Oh4aRO+JlfqMFNlXmUNXfklSnUB0BZWjUviDwkXn7m1HIaYv0ECpQpmCnoTjB8mu5mX8YPM00v9biS49/WdAqy3kojUzv+gZQNcppZT3FqlM8w1p2orVs7nm1Li7/sHqTmzl31+3rwRyIy0LhSYiBFSdPxO5jgX9Zcdv8cEh42TG8KH37Mjiz6ZcMC5ECobgI5WkwWOt0pPYC66RqMiDLSZV1giCyqUEWCY07x3p5sRonMuBxGZgMPo8gvRWJSVTZmMq+zg4v9ZonUMVNXGNEkO1FvBCSabQYjeyuMQM9Fa4pQiwYXbpUlIchAwIR9q427JiMRSfHCGT4T+pq5kqsw6KCcdBFBw4OX+O4H7pCoOwSb1OUscIwbVtXXB7G0CzyXzlj403OVpn/JQfD8nSgIKnd3W2AQzXCElSljMP98acsLx9rnHfT+fxTLOH8sQ6FdTsGXu9BKa4QJA5XO8M5t0sr1nRJeKs1AoZ6QtnXC8Xa9kkWoK4xAlKM0NShypD33AHyAkyWVxPbfE/aqW2VkRXR7Ts2ucyacuczSxesq5wG5bxRdQpma+pJcXuylkGAfVTGYnE5z0PgP+Yna0lBLfus02LyjmfIDb53L/VT97/fnJrpC3oVIQx+ue6mNc=
  file_golb: true
  file: out/mailman*
  skip_cleanup: true
  on:
    repo: xuqingfeng/mailman
    tags: true